;;;; bootstrap.lisp --- the seed: build the `cons` binary from the monorepo,
;;;; using nothing but SBCL. Run once (or whenever cons itself changes):
;;;;
;;;;     sbcl --dynamic-space-size 4096 --script bootstrap.lisp
;;;;
;;;; The command is IDENTICAL on Linux / macOS / Windows -- SBCL's CLI is uniform,
;;;; so there is no make / just / nmake anywhere in the chain. After this, `bin/cons`
;;;; drives build / test / serve / run for the whole tree (see the root cons build
;;;; spec, cons.lisp). It also WARMS the stack -- compiles every framework in DAG
;;;; order so the first `cons build` / editor load is instant, not a cold multi-minute
;;;; Coalton compile (skip with OURANOS_NO_WARM=1; the warm is cheap once fasls exist).
;;;; The only prerequisites are SBCL + a dependency source (Quicklisp now; ocicl later
;;;; for pinned, reproducible deps) -- installed by scripts/setup.{sh,ps1}, which then
;;;; call this file. That is the entire bootstrap: OS setup -> seed -> cons -> warm.

(require :asdf)

;;; --- the heap this seed needs (pre-publication issue 88) -----------------------------------------------
;;;
;;; SHARED with scripts/build-desktop-app.lisp rather than written twice. The whole finding
;;; was that 4096 lived in three places and the only copy a reader could get wrong was the
;;; one nobody checked; a second script with its own copy would have rebuilt that.
;;;
;;; What the flag actually does, since the documentation had it backwards: it is NOT needed
;;; to get the Coalton compile through -- that happens in the children below, which set
;;; their own heap. It matters because bin/cons inherits the heap of the process that dumps
;;; it and cannot be given another one afterwards. See scripts/heap-guard.lisp.

(load (merge-pathnames "scripts/heap-guard.lisp"
                       (uiop:pathname-directory-pathname
                        (or *load-truename* *load-pathname* (truename #p"./")))))

(ouranos-heap:ensure-heap (or *load-truename* *load-pathname*)
                          :reexec-var "OURANOS_BOOTSTRAP_REEXEC"
                          :what "bin/cons")

;;; SBCL contribs the framework tree loads on demand (Coalton -> sb-cltl2; the web
;;; stack's sockets -> sb-bsd-sockets; crypto/ironclad -> sb-rotate-byte/sb-md5; ...).
;;; A dumped STANDALONE executable cannot pull these from SBCL_HOME at runtime, so a
;;; later in-image `(require :sb-cltl2)` fails with "System sb-cltl2 not found". Bake
;;; them into the image NOW, while contribs are still reachable -- this is what makes
;;; `cons build` (in-process, in cons's warm image) able to compile Coalton and start
;;; the web server. (A `--fresh` subprocess sbcl gets them from SBCL_HOME instead.)
(dolist (contrib '(:sb-cltl2 :sb-bsd-sockets :sb-posix :sb-rotate-byte
                   :sb-md5 :sb-introspect :sb-concurrency))
  (ignore-errors (require contrib)))

;;; The whole monorepo tree is discoverable to ASDF in one shot -- no per-project
;;; local-projects symlinks. This is what replaces the per-framework symlinks at cutover.
(defparameter *root*
  (uiop:pathname-directory-pathname
   (or *load-truename* *load-pathname* (truename #p"./"))))

(asdf:initialize-source-registry
 `(:source-registry (:tree ,*root*) :inherit-configuration))

;;; ...and persist that discovery for *future* sessions. The form above only teaches
;;; THIS process; a plain `(ql:quickload :hyperion)` from an editor/REPL needs a
;;; standing config. We drop one ASDF `source-registry.conf.d` file pointing at this
;;; tree -- the monorepo-era replacement for symlinking each project into
;;; ~/quicklisp/local-projects. `xdg-config-home` resolves to the location ASDF
;;; actually reads on every OS (~/.config on Linux/macOS, %LOCALAPPDATA%\config on
;;; Windows). Machine-local (an absolute path), so it is NOT committed. Rewritten
;;; every bootstrap, so it self-heals if the repo moves.
(let ((conf (uiop:xdg-config-home "common-lisp" "source-registry.conf.d"
                                  "50-ouranos.conf")))
  (ensure-directories-exist conf)
  (with-open-file (out conf :direction :output
                            :if-exists :supersede :if-does-not-exist :create)
    ;; A conf.d file holds a SINGLE directive (no :source-registry wrapper, no
    ;; :inherit-configuration -- both are implied). Forward slashes so the Lisp
    ;; reader accepts the path on Windows too (backslash is its escape char).
    (format out ";;;; Generated by ouranos/bootstrap.lisp -- machine-local, do not commit.~%(:tree \"~A\")~%"
            (substitute #\/ #\\ (namestring *root*))))
  (format t "~&bootstrap: source-registry -> ~A~%" conf))

;;; The hub guard (AGENTS.md, "One agent, one working tree"). core.hooksPath is per-clone
;;; and not carried by git, so it has to be set by something everyone runs -- and this is
;;; the one command everyone runs. The hook itself refuses a commit on a non-main branch
;;; in the MAIN checkout only; a linked worktree has a `.git' FILE rather than a directory,
;;; so lanes are unaffected on any machine with no configuration of their own.
(let ((hooks (merge-pathnames ".githooks/" *root*)))
  (when (probe-file (merge-pathnames "pre-commit" hooks))
    (uiop:run-program (list "git" "-C" (namestring *root*)
                            "config" "core.hooksPath" ".githooks")
                      :ignore-error-status t)
    (format t "~&bootstrap: hub guard -> core.hooksPath=.githooks~%")))

;;; External deps (clingon, alexandria, ...) come from Quicklisp for now.
(load (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname)))
(funcall (read-from-string "ql:quickload") :cons/cli)

;;; Warm the stack: compile every framework NOW so the first `cons build` / editor
;;; load in each is instant, not a multi-minute Coalton compile. Run it in a THROWAWAY
;;; child sbcl on purpose -- loading Coalton + the web stack into THIS process would
;;; bake every framework into the lean cons image we are about to dump (bloat, and a
;;; cons->right DAG coupling). The child reads the source-registry drop-in written
;;; above; its fasls land in the shared ASDF cache, so the dumped bin/cons picks them
;;; up. Non-fatal (bin/cons is built either way) and skippable with OURANOS_NO_WARM=1
;;; for a quick cons-only rebuild. Up-to-date fasls make re-runs cheap (seconds).
(unless (uiop:getenvp "OURANOS_NO_WARM")
  (format t "~&bootstrap: warming the stack (aion..praxeon + hermes; minutes on a cold tree, seconds when warm)~%")
  (finish-output)
  (let ((code (nth-value 2
                (uiop:run-program
                 (list (namestring sb-ext:*runtime-pathname*)
                       "--dynamic-space-size" (princ-to-string ouranos-heap:*wanted-heap-mb*) "--non-interactive"
                       "--eval" "(require :asdf)"
                       "--load" (namestring (merge-pathnames "quicklisp/setup.lisp"
                                                             (user-homedir-pathname)))
                       "--eval" "(ql:quickload '(:aion :cons :mnemosyne :elenchon :hyperion :praxeon :hermes))"
                       "--eval" "(uiop:quit 0)")
                 :output :interactive :error-output :interactive :input :interactive
                 :ignore-error-status t))))
    (format t (if (eql code 0)
                  "~&bootstrap: stack warm.~%"
                  "~&bootstrap: warm step exited ~A -- continuing; bin/cons is still built.~%")
            code)))

;;; --- the host OS's platform package (pre-publication issue 182) ---------------------------------
;;; ECOSYSTEM.md: bootstrap compiles the host OS's platform package rather than leaving it
;;; opt-in the way aion/uv is. Opt-in there was BOUGHT by the C-toolchain requirement; a
;;; platform package has none (ADR-0003 s8), so deferring it buys nothing and costs a
;;; subsystem that goes uncompiled on the only OS where it can be compiled at all.
;;;
;;; The registry -- scripts/platform-packages.lisp, shared with verify-tree so the two
;;; cannot drift -- says which packages this host OWNS and how to read their absence.
;;; Absence is not one thing: a package that is DECIDED BUT UNWRITTEN is expected to be
;;; missing, while a package that exists and does not build here is a defect. They get
;;; different lines and different exit codes.
(load (merge-pathnames "scripts/platform-packages.lisp" *root*))

(let ((entries (funcall (read-from-string "ouranos-platform:entries-here")))
      (host    (funcall (read-from-string "ouranos-platform:host-os"))))
  (if (null entries)
      (format t "~&bootstrap: no platform packages are owned by this host (~(~A~)).~%" host)
      (dolist (entry entries)
        (let* ((system   (funcall (read-from-string "ouranos-platform:entry-system") entry))
               (status   (funcall (read-from-string "ouranos-platform:entry-status") entry))
               (issue    (funcall (read-from-string "ouranos-platform:entry-issue") entry))
               (findable (asdf:find-system system nil)))
          (cond
            ;; Decided but unwritten. Reported, never fatal -- a seed that refuses to run
            ;; because work has not started yet is a seed people stop running.
            ((and (eq status :planned) (not findable))
             (format t "~&bootstrap: ~A -- planned for this host, not in the tree yet (~A).~%"
                     system issue))
            ;; It landed and the registry did not notice. Say so where someone will read it.
            ((eq status :planned)
             (format t "~&bootstrap: ~A is PRESENT but the registry still says :planned -- flip it to :required in scripts/platform-packages.lisp (~A).~%"
                     system issue))
            ;; Owned by this host, declared required, and not here at all.
            ((not findable)
             (format t "~&bootstrap: ~A is REQUIRED on this host and ASDF cannot find it (~A).~%" system issue)
             (uiop:quit 1))
            (t
             (format t "~&bootstrap: building ~A (this host owns it)~%" system)
             (finish-output)
             ;; A child, for the same reason the warm step uses one: this image becomes
             ;; bin/cons, and a platform binding has no business being baked into it.
             (let ((code (nth-value 2
                          (uiop:run-program
                           (list (namestring sb-ext:*runtime-pathname*)
                                 "--dynamic-space-size" (princ-to-string ouranos-heap:*wanted-heap-mb*) "--non-interactive"
                                 "--eval" "(require :asdf)"
                                 "--load" (namestring (merge-pathnames "quicklisp/setup.lisp"
                                                                       (user-homedir-pathname)))
                                 ;; `ql:quickload', NOT `asdf:load-system'. ASDF can
                                 ;; only find what is already on disk, so a platform
                                 ;; system whose EXTERNAL dependencies are not
                                 ;; installed yet dies with MISSING-DEPENDENCY on a
                                 ;; cold machine. `aion/windows' requires cffi, and
                                 ;; under OURANOS_NO_WARM the warm step that would
                                 ;; have installed it is skipped -- so on a cold cache
                                 ;; with NO_WARM set, which is exactly what
                                 ;; desktop-release.yml asks for, nothing installs it
                                 ;; at all. Measured: run 35211034442, windows leg,
                                 ;; MISSING-DEPENDENCY :REQUIRED-BY "aion/windows"
                                 ;; :REQUIRES "cffi". It had gone unseen because that
                                 ;; workflow had not run since before `aion/windows'
                                 ;; became :required, and its cache had been evicted.
                                 ;;
                                 ;; Every other load in this file already uses
                                 ;; quickload; this line was the one that did not, and
                                 ;; it is also the only one that runs on exactly one
                                 ;; host -- so it is the one a matrix cannot cover for
                                 ;; you. Quickload still
                                 ;; resolves the system itself from the TREE -- it is in
                                 ;; no Quicklisp dist -- and installs only what it
                                 ;; depends on.
                                 "--eval" (format nil "(ql:quickload ~S)" system)
                                 "--eval" "(uiop:quit 0)")
                           :output :interactive :error-output :interactive :input :interactive
                           :ignore-error-status t))))
               ;; FATAL, unlike the warm step. The warm step is an optimisation and the tree
               ;; still works without it; this is the one machine that can compile this
               ;; package, so a failure here is the finding, not a slow first build.
               (unless (eql code 0)
                 (format t "~&bootstrap: ~A FAILED to build on the host that owns it (exit ~A).~%" system code)
                 (uiop:quit 1))
               (format t "~&bootstrap: ~A ok.~%" system))))))))

;;; --- the native webview launcher (#13) -------------------------------------
;;; A desktop app opens its window through hyperion-view, a small C++ program that is build
;;; output and gitignored, so a fresh clone does not have it. Before this step nothing said
;;; so until a window failed to open. Build it here when the host has the toolchain; when it
;;; does not, show the build script's prerequisite report and the command to run later.
;;;
;;; NOT FATAL, unlike a platform package above. Only desktop apps need the launcher, and a
;;; machine without a C++ toolchain can still build and serve everything else. Skip it with
;;; OURANOS_SKIP_VIEW_BUILD=1, the same variable scripts/verify-tree.lisp reads.
;;;
;;; The build is scripts/view-launcher.lisp, shared with verify-tree.lisp. It runs as a child
;;; process, so nothing from it enters the bin/cons image. Measured on Windows (MSVC): about
;;; 5 s cold, including a 9 MB WebView2 SDK fetch (46 MB unpacked), and about 3 s once the SDK is cached.
(load (merge-pathnames "scripts/view-launcher.lisp" *root*))

(let ((windows (uiop:os-windows-p)))
  (format t "~&bootstrap: building the native webview launcher (hyperion-view)~%")
  (finish-output)
  ;; The check runs quietly because the build script repeats the same report before it
  ;; compiles. When the check fails, it runs again with its output shown, so the report
  ;; saying which prerequisite is missing, and how to install it, is printed here.
  (multiple-value-bind (state reason)
      (funcall (read-from-string "ouranos-view:run-build") *root* :output :interactive)
    (let ((path (uiop:native-namestring
                 (funcall (read-from-string "ouranos-view:launcher-path") *root*))))
      (case state
        (:built
         (format t "~&bootstrap: launcher built -> ~A~%" path))
        (:skipped
         (format t "~&bootstrap: launcher skipped (OURANOS_SKIP_VIEW_BUILD is set).~%"))
        (t
         (when (eq state :unavailable)
           (uiop:run-program (funcall (read-from-string "ouranos-view:build-command") *root*
                                      :check t
                                      :shell (funcall (read-from-string "ouranos-view:powershell")))
                             :output :interactive :error-output :interactive
                             :ignore-error-status t))
         (format t "~&bootstrap: launcher NOT built: ~A~%" reason)
         (format t "~&bootstrap: desktop windows will not open until it is. From the tree root: ~A~%"
                 (funcall (read-from-string "ouranos-view:build-hint") windows)))))))

;;; Dump the tool image. When cons/cli:main returns, SBCL exits -- so the binary
;;; runs `cons`, not a REPL. `:save-runtime-options t` is essential: without it the
;;; executable still parses SBCL's OWN runtime flags first, so `bin/cons --help` /
;;; `--version` would print SBCL's help and never reach the CLI. With it, every arg
;;; goes to `cons` (clingon), and the 4 GB heap in effect here is baked in -- handy
;;; once `cons build` loads Coalton systems.
(let ((bin (merge-pathnames (if (uiop:os-windows-p) "bin/cons.exe" "bin/cons") *root*)))
  (ensure-directories-exist bin)
  (format t "~&bootstrap: saving cons -> ~A~%" bin)
  (sb-ext:save-lisp-and-die
   bin
   :toplevel (fdefinition (read-from-string "cons/cli:main"))
   :executable t
   :save-runtime-options t))
