;;;; elise.lisp --- Elise: a modern-psychology successor to ELIZA
;;;;
;;;; Weizenbaum named ELIZA after Eliza Doolittle -- the pupil who could be
;;;; taught to speak ever better -- and its Rogerian script was called DOCTOR.
;;;; The joke was that DOCTOR only *appeared* to understand; it matched patterns
;;;; and reflected them back. Elise keeps the reflective spirit but escapes the
;;;; hard-coded stigma: the reflection is generated by an LLM prompted to draw on
;;;; modern, evidence-based psychology (reflective listening, validation, gentle
;;;; reframing, motivational interviewing).
;;;;
;;;; IMPORTANT: Elise is a demonstration of the Praxeon actor model, NOT a
;;;; therapist and NOT a substitute for professional mental-health care. She
;;;; includes a lightweight safety guardrail that surfaces crisis resources.

(cl:defpackage #:praxeon/elise
  (:use #:cl)
  (:local-nicknames (#:config #:praxeon/config)
                    (#:llm #:praxeon/llm)
                    (#:actor #:praxeon/actor)
                    (#:turn #:praxeon/turn)
                    (#:evt #:praxeon/event)
                    (#:studio #:praxeon/studio)
                    (#:web #:praxeon/web)
                    (#:web-search #:praxeon/web-search)
                    (#:translate #:praxeon/translate)  ; converse in the user's locale
                    (#:i18n #:hyperion/i18n))   ; the web chrome is localized (en/es)
  (:export #:start #:serve #:start-web #:dev #:main #:make-elise
           #:*system-prompt* #:*crisis-resources*))

(cl:in-package #:praxeon/elise)

(defparameter *system-prompt*
  "You are Elise, a warm, attentive clinical *intake* assistant. Your role is to help
a person get ready for a new visit by gathering, in an unhurried and human way, the
information a clinician will want -- so the visit itself can focus on care.

IMPORTANT -- this is a DEMONSTRATION, not a real clinical setting. You are not a
clinician; you do not diagnose, prescribe, or give medical advice, and nothing here
is a substitute for professional care. The visit is fictitious and so is anything
the person shares. Never state or imply a diagnosis to the person.

How you work:
- Open briefly and kindly: explain you'll ask a few questions to help prepare for
  their visit, that everything here is a demonstration, and that they can skip
  anything or stop at any time.
- Gather the intake picture conversationally -- one thing at a time, at their pace:
  the main reason for the visit (the chief concern), when it began and how it has
  changed, what makes it better or worse, relevant history, current medications and
  allergies, and anything they feel matters. Ask open questions; follow their lead;
  never interrogate.
- Reflect and recap to confirm you have understood ('So the main thing is ... -- did
  I get that right?'). Accuracy matters more than speed.
- Stay in your lane: you *collect and organize*; the clinician *assesses*. If asked
  for advice or a diagnosis, gently redirect -- that is for their clinician, whom
  this conversation helps prepare them to see.
- Be honest and kind; never pretend to certainty. If you do not understand a term,
  ask -- or, if web search is available, look up a neutral definition, always noting
  you are not a clinician.
- Safety first: if the person may be in crisis or at risk of harm, gently encourage
  them to reach out to a professional or a trusted person now, and share crisis
  resources.

Keep replies concise and human. Avoid lists unless they genuinely help the person.")

(defparameter *crisis-resources*
  "If you're in immediate danger or thinking about harming yourself, please
reach out right now to local emergency services, or a crisis line such as 988
(Suicide & Crisis Lifeline, US). You deserve support from a real person, and
talking to someone can help."
  "Message surfaced by the safety guardrail. Localize as appropriate.")

(defparameter *crisis-cues*
  '("suicid" "kill myself" "end my life" "self-harm" "self harm"
    "hurt myself" "want to die" "no reason to live")
  "Very rough substring cues. A real system would use a proper classifier; this
is a conservative, transparent placeholder that errs toward offering help.")

(defun looks-like-crisis-p (text)
  "True if TEXT contains any crisis cue (case-insensitive substring)."
  (let ((down (string-downcase text)))
    (some (lambda (cue) (search cue down)) *crisis-cues*)))

(defun make-elise (&key provider)
  "Build an Elise agent (the therapist role). With no PROVIDER, one is built for the
\"elise\" role: PRAXEON_ELISE_{IMPL,MODEL,API_KEY,...} if set, else the shared
PRAXEON_LLM_* (see praxeon/llm:make-provider-from-env) -- so Elise's model is
configured independently of the translator and any other agents. The project .env is
loaded first, resolved via ASDF so it is found no matter the working directory. When a
TAVILY_API_KEY is configured, Elise also gets the web-search means."
  (config:load-dotenv
   :path (merge-pathnames ".env" (asdf:system-source-directory "praxeon")))
  (let ((agent (actor:make-agent :name "Elise"
                                 :provider (or provider
                                               (llm:make-provider-from-env :role :elise))
                                 :system-prompt *system-prompt*)))
    ;; A Means toward the End of understanding the user: search the web to clarify
    ;; an unfamiliar term/reference. Only when a key is set (no key -> no tool).
    (when (uiop:getenv "TAVILY_API_KEY")
      (web-search:register agent))
    agent))

(defvar *translator* nil "Cached translation provider (built on first non-English turn).")
(defun translator ()
  (or *translator* (setf *translator* (translate:make-translator))))

(defun crisis-note (locale)
  "The crisis resources in LOCALE (from the same i18n dictionary as the web footer)."
  (t* locale :web/crisis))

(defun crisis-guardrail ()
  "The safety guardrail, as a LEAVE stage.

It was an `if` at the bottom of a `let*` that APPENDED resources to whatever Elise had
already said. As a leave stage it sees the finished turn and can amend it deliberately --
and, more to the point, it is now a value: reorderable, reusable, and testable without a
model or a network.

It reads TURN-INPUT rather than the original argument, which is what makes the ordering
constraint safe instead of merely commented. The cues are English, so the check is only
correct once the input has been rendered to English; the effect stores that English text
back into the turn, so a guardrail reading TURN-INPUT is reading the text the cues were
written for."
  (turn:leave-stage
   "crisis"
   (lambda (tn)
     (if (looks-like-crisis-p (turn:turn-input tn))
         (let ((locale (intern (string-upcase (turn:turn-locale tn)) :keyword)))
           (turn:with-reply tn (format nil "~A~2%~A"
                                       (turn:turn-reply tn) (crisis-note locale))))
         tn))))

(defun %elise-effect (agent)
  "The single impure pivot of an Elise turn: translate in, deliberate, translate out.

Elise always deliberates in English, so her history and her guardrail stay in one
language. The English text is written back into the turn with WITH-INPUT so that later
stages -- the crisis check above -- see what the model actually saw rather than the
user's original."
  (lambda (tn)
    (let* ((locale (intern (string-upcase (turn:turn-locale tn)) :keyword))
           (en? (eq locale :en))
           (tr (unless en? (translator)))
           (en-input (if en?
                         (turn:turn-input tn)
                         (translate:translate tr (turn:turn-input tn) :en :from locale)))
           (en-reply (actor:run-turn agent en-input))
           (reply (if en? en-reply (translate:translate tr en-reply locale :from :en))))
      (turn:with-reply (turn:with-input tn en-input) reply))))

(defun respond (agent user-input &optional (locale :en))
  "One Elise turn in the user's LOCALE, with the safety guardrail around deliberation.

Composed as an interceptor chain over a PRAXEON/TURN context (pre-publication issue 130) rather than as a
`let*`. The previous version said in this docstring that it *was* a pipeline -- translate
in, run the turn, guardrail on the way out -- while being a sequence of bindings that
could not be reordered, inspected or short-circuited. Now it is the thing it claimed.

Returns the reply text; RESPOND-TURN returns the whole turn if a caller needs to know
whether a stage refused."
  (turn:turn-reply (respond-turn agent user-input locale)))

(defun respond-turn (agent user-input &optional (locale :en))
  "RESPOND, but returning the TURN -- so a caller can ask whether it was refused
(TURN:TURN-HALTED) and why (TURN:TURN-NOTE) rather than parsing the reply."
  (turn:run-chain (list (crisis-guardrail))
                  (%elise-effect agent)
                  (turn:make-turn user-input (string-downcase (symbol-name locale)))))

(defparameter *quit-commands* '(":quit" "quit" "exit" "bye" "q")
  "Whole-line inputs (case-insensitive) that end an Elise session.")

(defun %quit-p (line)
  "True if LINE is end-of-input or one of *QUIT-COMMANDS*."
  (or (eq line :quit)                    ; EOF (Ctrl-D)
      (and (stringp line)
           (member (string-trim '(#\Space #\Tab) line) *quit-commands*
                   :test #'string-equal))))

(defun start (&key provider (stream *query-io*))
  "Open an interactive session with Elise. Type :quit (or exit/quit/bye/q), or
press Ctrl-D, to end. Provider config comes from the PRAXEON_LLM_* environment
unless PROVIDER is supplied."
  (let ((agent (make-elise :provider provider)))
    (format stream "~&Elise -- a kind, reflective companion (at present a Praxeon demo, definitely not therapy).~%")
    (format stream "Type :quit (or exit / quit / bye) to end.~2%")
    ;; Report what Elise is doing between request and response.
    (evt:with-observer ((studio:status-observer stream))
      (loop
        (format stream "~&you> ")
        (finish-output stream)
        (let ((line (read-line stream nil :quit)))
          (when (%quit-p line)
            (format stream "~&Take care.~%")
            (return))
          (handler-case
              (format stream "~&Elise> ~A~2%" (respond agent line))
            (praxeon/conditions:praxeon-error (e)
              (format stream "~&[error] ~A~%" e))))))))

;;; --- Web chrome i18n --------------------------------------------------------
;;; The web title/intro/footer are localized through hyperion/i18n -- the same
;;; machinery a consuming app uses. Adding a language = drop a resources/i18n/<code>.json
;;; file; the language switcher and per-request negotiation (?lang= / cookie /
;;; Accept-Language) are handled by praxeon/web when a dictionary is supplied.
;;; (The CLI path and the crisis guardrail stay English for now; the guardrail
;;; gets locale-aware when it moves into the typed interceptor pipeline.)

(defvar *dict* nil "Elise's web-chrome dictionary (en, es); loaded on first use.")

(defun dict ()
  "Elise's i18n dictionary, loading examples/elise/resources/i18n/*.json on first
use. Resolved via ASDF so it is found no matter the working directory."
  (or *dict*
      (setf *dict*
            (i18n:load-dictionary
             (merge-pathnames "examples/elise/resources/i18n/"
                              (asdf:system-source-directory "praxeon"))
             :default :en))))

(defun t* (locale key &rest args)
  "Translate flat KEY (:section/key) in LOCALE from Elise's dictionary."
  (apply #'i18n:translate (dict) locale key args))

(defparameter *web-theme*
  ".message.px-assistant .message-header{background-color:#d6336c}.message.px-assistant .message-body{background-color:#fff0f5;border-color:#f2a5c0;color:#4a1f33}"
  "Elise's warm rose accent -- app-level styling, passed to praxeon/web:start as
:theme-css so it overrides the neutral .px-assistant bubble. Her personality color
lives here, not in the generic web layer.")

(defun %web-arguments (&key (agent (make-elise)) dev)
  "The keyword arguments that define Elise's web surface, in ONE place.

START-WEB and SERVE differ only in whether they block; what they serve is identical. Two
copies of this list would be two Elises, and the one that drifted would be the one only the
shipped binary runs -- nobody drives `--server' interactively, so nobody would notice."
  (list :agent agent
        :responder (lambda (a msg locale) (respond a msg locale))
        :agent-name "Elise"
        ;; Localized chrome: title/intro/footer are functions of the request
        ;; locale, resolved per request by praxeon/web from the dictionary.
        :dictionary (dict)
        :title (lambda (loc) (t* loc :web/title))
        :intro (lambda (loc) (t* loc :web/intro))
        ;; persistent footer: the demoware disclaimer + crisis resources
        :footer (lambda (loc) (format nil "~A  ·  ~A"
                                      (t* loc :web/disclaimer)
                                      (t* loc :web/crisis)))
        ;; entry gate: acknowledge the fictitious/demo nature before chatting
        :gate (lambda (loc) (list :title (t* loc :web/gate-title)
                                  :body (t* loc :web/gate-body)
                                  :accept (t* loc :web/gate-accept)))
        :theme-css *web-theme*
        :dev dev))

(defun start-web (&key (port web:*default-port*) (host "127.0.0.1") dev
                       (agent (make-elise)))
  "Start Elise's web app on a background thread and RETURN the Clack handler
(non-blocking) -- the REPL-friendly entry, e.g. for hot-swap development. Stop it
with (praxeon/web:stop <handler>). The responder is a *by-name* call to RESPOND,
so recompiling RESPOND is picked up by the running server; pass :dev t to make the
page auto-refresh on (praxeon/web:mark-reloaded).

The conversation lives in AGENT, not the server. Pass an existing agent to keep
its history across a stop/restart -- essential for hot-swap dev, where you restart
the server to pick up a handler change but want to keep chatting:

    (defparameter *elise* (praxeon/elise:make-elise))   ; state lives here
    (defparameter *h* (praxeon/elise:start-web :agent *elise* :dev t))
    ;; ... recompile, (praxeon/web:stop *h*), start-web :agent *elise* again ...

With no :agent a fresh one is built. SERVE is the blocking entry."
  (apply #'web:start (append (%web-arguments :agent agent :dev dev)
                             (list :port port :host host))))

(defun dev (&key (port web:*default-port*) (host "127.0.0.1")
                 (agent (make-elise)) watch-frameworks)
  "One call for hot-reload development. Keeps a PERSISTENT Elise agent and watches
the source tree: edit src/*.lisp or this file, save, and the changed files
recompile and the web app restarts around the *same* agent -- the browser
refreshes and the conversation is preserved. Open http://HOST:PORT and chat while
you edit. Stop with (praxeon/web:unwatch). AGENT lets you supply/keep one. HOST
defaults to 127.0.0.1 (localhost); pass \"0.0.0.0\" to reach it from another machine.

WATCH-FRAMEWORKS t ALSO watches Hyperion's src/, so framework edits hot-reload too
-- for co-developing Hyperion alongside Praxeon. This is an edge case; leave it off
(the default) for normal work, where Hyperion is a stable dependency."
  (let ((elise agent)
        (root (asdf:system-source-directory "praxeon")))
    (web:watch (lambda () (start-web :agent elise :dev t :port port :host host))
               :paths (list (merge-pathnames "src/" root)
                            (merge-pathnames "examples/elise/" root))
               :systems (when watch-frameworks '("hyperion")))))

(defun serve (&key (port web:*default-port*) (host "127.0.0.1") (agent (make-elise)))
  "Run Elise as a web app (HTMX chat + REST) and BLOCK until interrupted (Ctrl-C)
-- the entry the bin/elise --server binary uses. The turn goes through RESPOND, so
the crisis guardrail applies as in the CLI. For REPL/hot-swap work use START-WEB,
which returns immediately.

This used to hand-roll the blocking part: a banner, `(loop (sleep 3600))', and a handler for
`interactive-interrupt'. That answers Ctrl-C and nothing else -- no shutdown hooks, no
restored signal handlers, and a supervisor's SIGTERM could only be answered by killing the
process (pre-publication issue 151). `praxeon/web:serve-forever' owns all of it now, and the banner comes from
:name rather than from a FORMAT here that could disagree with the port actually bound."
  (apply #'web:serve-forever (append (%web-arguments :agent agent)
                                     (list :port port :host host))))

(defun %server-invocation ()
  "Parse the executable's argv: return (values server-p port host). `--server`
selects web mode; `--port N` overrides the port; `--host ADDR` the bind address --
default 127.0.0.1 (localhost only); pass 0.0.0.0 to accept LAN/remote connections."
  (let ((args (uiop:command-line-arguments)))
    (flet ((opt (name) (second (member name args :test #'string=))))
      (values (and (member "--server" args :test #'string=) t)
              (or (ignore-errors (parse-integer (opt "--port"))) web:*default-port*)
              (or (opt "--host") "127.0.0.1")))))

(defun main ()
  "Standalone entry point for the bin/elise executable (built by the Makefile
`elise` target). Loads a .env from the current directory if present, then runs
either an interactive CLI session (default) or, with
`--server [--port N] [--host ADDR]`, the web app. Exits with a POSIX status."
  (handler-case
      (multiple-value-bind (server-p port host) (%server-invocation)
        (config:load-dotenv)   ; cwd .env; shell env and the project .env also apply
        (if server-p (serve :port port :host host) (start))
        (uiop:quit 0))
    (praxeon/conditions:praxeon-error (e)
      (format *error-output* "~&[error] ~A~%" e)
      (uiop:quit 1))
    #+sbcl
    (sb-sys:interactive-interrupt ()
      (format *error-output* "~&Interrupted.~%")
      (uiop:quit 130))))
