;;;; init.lisp --- `cons init`: scaffold a new project (the "just works" skeleton).
;;;;
;;;; Generates the exact founding layout these projects hand-rolled: the .asd + a
;;;; package-per-module src/, tests/, a hardened .gitignore (with the .env rules), a
;;;; committed .env.example (closing the loop with cons/env:load-dotenv), the .vscode
;;;; Alive config, a `cons.lisp` build spec (the cross-OS Makefile replacement), and
;;;; README/CLAUDE skeletons. A --template picks the dependency set and the emitted
;;;; targets (lib | cli | web | agent); :web scaffolds a minimal, runnable Hyperion
;;;; app. Pure file emission (no deps beyond uiop), so it stays in the cons core; the
;;;; CLI (cons/cli) drives it.

(in-package #:cons/init)

(defparameter *default-author* "Bob <eternal.recursion@proton.me>"
  "Author line stamped into generated .asd/README when none is supplied.")

;;; --- target kinds ----------------------------------------------------------
;;;
;;; A TARGET KIND is what `cons build` / `run` / `ship` DO. A TEMPLATE is what files you
;;; start with. They are independent, and conflating them is what `--template web` does
;;; today: a SaaS app and a landing page are the same target kind and completely different
;;; templates (docs/templates-design.md §2).
;;;
;;; Kinds are small, closed and versioned with cons; templates are open-ended and will be
;;; authored by third parties. `cli` and `agent` already demonstrate the split -- same
;;; kind, different dependencies -- which is why this refactor changes no generated byte.

(defstruct (target-kind (:constructor %make-target-kind) (:copier nil))
  "What a target kind contributes to generation. The verbs themselves (`ship` producing an
installer, a service registering with the SCM) live outside this file; what a kind decides
HERE is whether the project has an entry point and what its cons.lisp offers."
  (name nil :read-only t)
  ;; Executable kinds get a MAIN, a `bin` target, and the out-of-image dump script.
  (executable-p nil :read-only t)
  (spec-params "" :read-only t)      ; the :params clause for the generated cons.lisp
  (extra-targets "" :read-only t)    ; extra target forms for the generated cons.lisp
  (run-line "" :read-only t)         ; the README's Develop hint
  ;; Declared kinds with no scaffolding yet. A template may still name one: files and an
  ;; honest "the ship path is not built" beat the kind not existing (design §3).
  (implemented-p t :read-only t))

(defparameter *target-kinds* '()
  "Every target kind cons knows, most useful first. Populated below, after the snippets
those kinds are made of.")

(defun find-target-kind (name)
  "The TARGET-KIND named NAME, or NIL."
  (find name *target-kinds* :key #'target-kind-name))

(defun target-kind-names ()
  (mapcar #'target-kind-name *target-kinds*))

;;; --- tiny templating (token replacement; no format-directive escaping) -----

(defun %replace-all (string part replacement)
  (with-output-to-string (out)
    (loop with plen = (length part)
          for pos = 0 then (+ found plen)
          for found = (search part string :start2 pos)
          do (write-string string out :start pos :end (or found (length string)))
          while found do (write-string replacement out))))

(defparameter +dev-port-base+ 20000
  "Bottom of the block generated dev ports are drawn from.")
(defparameter +dev-port-span+ 10000
  "Size of that block, so ports land in 20000-29999.

Chosen to sit BELOW every OS ephemeral range -- Windows starts at 49152, Linux at 32768 --
so a generated port can never collide with one the operating system hands to something
else by accident. It is also clear of 8080 and the rest of the range every other tool on a
developer's machine wants.")

(defun dev-port (name)
  "A stable development port for a project called NAME.

THE LITERAL IN A TEMPLATE IS THE DEFECT, not the collision it produces (pre-publication issue 238). A fixed
port in a template file guarantees that every application generated from it wants the same
one -- and when two are open at once the second window shows the FIRST application: its
title, its routes, and a 404 for everything the second added. That reads as a
catastrophically broken build, because nothing in the symptom points anywhere near a port.

FNV-1a rather than SXHASH, deliberately: SXHASH's value for a string is not promised to be
stable across SBCL versions, and a project regenerated next year should get the port it has
in its README today. The sharper consequence is not about time but about PEOPLE -- two
developers on different SBCL versions would derive DIFFERENT ports from the same project
name, so the app would come up on one machine and not the other with nothing in the source
to explain it. A works-on-my-machine defect with no visible cause is worse than the
collision this function exists to prevent. This is derivation, not a guarantee of uniqueness -- two names can
collide, which is why HYPERION/SERVER:START also refuses a port that is already answering.
The derivation makes collisions rare; the preflight makes them harmless."
  (let ((hash 2166136261))
    (loop for ch across (string-downcase (string name))
          do (setf hash (logand #xffffffff
                                (* (logxor hash (char-code ch)) 16777619))))
    (+ +dev-port-base+ (mod hash +dev-port-span+))))

(defun %fill (template subs)
  "Replace each (\"{{marker}}\" . value) pair of SUBS throughout TEMPLATE."
  (let ((out template))
    (dolist (pair subs out)
      (setf out (%replace-all out (car pair) (cdr pair))))))

;;; --- walking a template's file tree ----------------------------------------

(defun %tree-files (root)
  "Every file under ROOT, as namestrings RELATIVE to it, in a stable order.
Sorted so a scaffold reports the same sequence twice running -- directory order is not
guaranteed, and a diffable log is worth more than the microsecond.

ROOT is resolved to its truename first, and that is not a tidiness measure. ENOUGH-PATHNAME
relativises by comparing directory components, so it needs BOTH sides to spell the
directory the same way -- and on Windows they need not. A GitHub Actions runner sets TEMP to
the 8.3 SHORT form (C:\\Users\\RUNNER~1\\...) while DIRECTORY-FILES answers with the long one;
case can differ too. When the comparison fails ENOUGH-PATHNAME returns the file ABSOLUTE and
says nothing, and an absolute `relative path' then defeats the (MERGE-PATHNAMES destination
root) at the call site -- MERGE-PATHNAMES keeps the absolute one, so every scaffolded file
is written back into the TEMPLATE directory instead of the target. The scaffold reports
success; the target is empty (pre-publication issue 185)."
  (let* ((root (uiop:ensure-directory-pathname root))
         ;; PROBE-FILE answers the truename, which settles short-vs-long and case both.
         (base (or (probe-file root) root))
         (files '()))
    (uiop:collect-sub*directories
     base t t
     (lambda (dir)
       (dolist (file (uiop:directory-files dir))
         (let ((rel (uiop:enough-pathname file base)))
           ;; Belt and braces, and deliberately LOUD. If relativising ever fails again the
           ;; harm is writing outside the target, which a silent absolute path buys us; an
           ;; error costs a stack trace naming the two paths that disagree.
           (when (uiop:absolute-pathname-p rel)
             (error "cons: cannot express~%  ~A~%relative to~%  ~A~%Refusing to scaffold rather than write outside the target."
                    (uiop:native-namestring file) (uiop:native-namestring base)))
           (push (uiop:native-namestring rel) files)))))
    (sort files #'string<)))

(defparameter +inert-suffix+ ".tmpl"
  "A template file whose name ends in this is written without it: `{{name}}.asd.tmpl' becomes
`myapp.asd'.

It exists for files that a tool would otherwise pick up from inside the template directory.
The built-in templates ship their system definition as `{{name}}.asd.tmpl' because a file
named `{{name}}.asd' is one ASDF finds: with the repository on the source registry, the four
built-ins defined four systems named `{{name}}', and ASDF warned about the duplicates in any
session whose first source-registry scan happened inside a REQUIRE, such as the second run of
bootstrap.lisp (#108). Any template file can use the suffix; a file without it is written
under its own name, so an existing template that ships `{{name}}.asd' still works. The suffix
is removed once, so a file that really ends in `.tmpl' is named `X.tmpl.tmpl' in the
template.")

(defun %substitute-path (relpath subs)
  "Fill markers in a RELATIVE PATH, and drop +INERT-SUFFIX+ from its end. Templates carry
{{name}} in file names as well as in contents -- `{{name}}.asd.tmpl` is the obvious one."
  (let ((filled (%fill (substitute #\/ #\\ relpath) subs)))
    (if (and (> (length filled) (length +inert-suffix+))
             (string= +inert-suffix+ filled :start2 (- (length filled) (length +inert-suffix+))))
        (subseq filled 0 (- (length filled) (length +inert-suffix+)))
        filled)))

(defun %copy-file (source destination subs)
  "Copy SOURCE to DESTINATION, filling markers in its contents.

A file that is not valid UTF-8 is copied BYTE FOR BYTE instead. Built-in templates are all
text, but a landing-page template will carry a logo, and silently corrupting it while
looking for `{{name}}` would be a poor introduction to authoring templates."
  (ensure-directories-exist destination)
  (let ((text (handler-case
                  (uiop:read-file-string source :external-format :utf-8)
                (error () nil))))
    (if text
        (with-open-file (out destination :direction :output :if-exists :supersede
                                         :if-does-not-exist :create :external-format :utf-8)
          (write-string (%fill text subs) out))
        (with-open-file (in source :element-type '(unsigned-byte 8))
          (let ((bytes (make-array (file-length in) :element-type '(unsigned-byte 8))))
            (read-sequence bytes in)
            (with-open-file (out destination :direction :output :if-exists :supersede
                                             :if-does-not-exist :create
                                             :element-type '(unsigned-byte 8))
              (write-sequence bytes out)))))))

;;; --- templates -------------------------------------------------------------
;;;
;;; A template names its target kind and its dependency set. Everything else about a
;;; built-in is still code here; step 2 of the design moves the files themselves to disk,
;;; at which point built-ins stop being special and a third party can author one.

(defstruct (template (:constructor %make-template) (:copier nil))
  "A project template: a DIRECTORY plus a manifest, never Lisp inside cons.

The built-ins are ordinary templates living in cons/templates/; nothing about them is
privileged, which is the point -- whatever cons does to find and expand its own is exactly
what it will do for one someone else wrote (design §4)."
  (name nil :read-only t)
  (target-kind nil :read-only t)     ; a keyword naming a TARGET-KIND
  (dependencies '() :read-only t)
  (description "" :read-only t)
  (directory nil :read-only t))      ; holds template.lisp and files/

(defun template-files-root (template)
  (merge-pathnames "files/" (template-directory template)))

(defun builtin-template-directory ()
  "Where the templates shipped with cons live.

NOTE for the dumped binary: this resolves through ASDF, so `bin/cons` finds these only
while the source tree is present. Making the built-ins available to a standalone binary is
a packaging question (embed them, or ship them beside it) and is deliberately not answered
here -- it belongs with the same decision for `cons conform`'s pack."
  (asdf:system-relative-pathname :cons "templates/"))

(defun %read-manifest (path)
  "Read a template manifest: ONE plist, read as data.

*READ-EVAL* is off and nothing is evaluated. A template that can run code is a
supply-chain problem the moment templates resolve by URL (design §4), so the format is
declarative by construction rather than by convention -- there is no hook to put code in."
  (with-open-file (in path :external-format :utf-8 :if-does-not-exist nil)
    (unless in
      (error "No template manifest at ~A." (namestring path)))
    ;; NOT the KEYWORD package, tempting as it is for a plist: reading `nil` there yields
    ;; the keyword :NIL rather than the empty list, so `:dependencies ()` would arrive as a
    ;; non-empty non-list and every dependency-free template would generate a broken .asd.
    (let ((form (with-standard-io-syntax
                  (let ((*read-eval* nil)
                        (*package* (find-package '#:cons/init)))
                    (read in nil nil)))))
      (unless (and (consp form) (evenp (length form)))
        (error "~A: expected a property list, got ~S." (namestring path) form))
      form)))

(defun load-template (directory)
  "Load the template in DIRECTORY (which holds template.lisp and files/)."
  (let* ((dir (uiop:ensure-directory-pathname directory))
         (manifest (%read-manifest (merge-pathnames "template.lisp" dir)))
         (name (getf manifest :name))
         (kind (getf manifest :target-kind)))
    (unless name
      (error "~Atemplate.lisp: :name is required." (namestring dir)))
    (unless kind
      (error "~Atemplate.lisp: :target-kind is required (one of ~{~(~A~)~^ ~})."
             (namestring dir) (target-kind-names)))
    (unless (uiop:directory-exists-p (merge-pathnames "files/" dir))
      (error "~A has a manifest but no files/ directory." (namestring dir)))
    (%make-template :name (if (stringp name) (intern (string-upcase name) :keyword) name)
                    :target-kind kind
                    :dependencies (getf manifest :dependencies)
                    :description (or (getf manifest :description) "")
                    :directory dir)))

(defun builtin-templates ()
  "Every template shipped with cons, discovered rather than listed: adding one is adding a
directory, and forgetting to register it is not a failure mode that exists."
  (sort (loop for dir in (uiop:subdirectories (builtin-template-directory))
              when (probe-file (merge-pathnames "template.lisp" dir))
                collect (load-template dir))
        #'string< :key (lambda (tm) (string (template-name tm)))))

(defvar *templates* nil
  "The built-in templates, loaded on first use. NIL forces a reload -- which is what a
REPL session wants after editing one.")

(defun templates ()
  (or *templates* (setf *templates* (builtin-templates))))

(defun find-template (name)
  "The built-in TEMPLATE named NAME, or NIL. NAME may be a keyword or a string."
  (let ((key (if (stringp name) (intern (string-upcase name) :keyword) name)))
    (find key (templates) :key #'template-name)))

(defun resolve-template (designator)
  "The template DESIGNATOR names: a built-in by name, or a DIRECTORY holding a manifest.

The directory case is what makes a template authorable outside cons today; resolving a git
URL or an OCI artifact is the same seam, one step later (design §4, #32)."
  (etypecase designator
    ((or keyword string)
     (let ((path (and (stringp designator)
                      (uiop:directory-exists-p (uiop:ensure-directory-pathname designator)))))
       (cond (path (load-template path))
             ((find-template designator))
             (t (error "Unknown template ~S; expected one of ~{~(~A~)~^ ~}, or a directory."
                       designator (template-names))))))
    (pathname (load-template designator))))

(defun template-names ()
  (mapcar #'template-name (templates)))

(defun template-kind (template)
  "The TARGET-KIND structure TEMPLATE declares. Signals if a template names a kind that
does not exist -- which is a bug in the template, and silence would make it a bug in the
generated project instead."
  (or (find-target-kind (template-target-kind template))
      (error "Template ~S declares unknown target kind ~S; known kinds: ~{~S~^ ~}."
             (template-name template) (template-target-kind template)
             (target-kind-names))))

(defun %render-deps (deps)
  "Render DEPS as the body of an .asd :depends-on list (indented, or empty)."
  (if (null deps)
      ""
      (format nil "~{\"~A\"~^~%               ~}" deps)))

;;; --- what a TARGET KIND injects -------------------------------------------
;;;
;;; These stay in code, unlike the file templates: kinds are closed and versioned with
;;; cons, and a template's own cons.lisp asks for them by marker ({{targets-extra}} and
;;; friends). That is how a third-party template gets the right build targets for its
;;; kind without having to know what they are.

(defparameter *spec-params-web*
"
  :params ((host \"127.0.0.1\" :doc \"web bind address; 0.0.0.0 to reach it from the LAN\"))"
  "The :params clause (a HOST knob) injected into a :web project's cons.lisp.")

(defparameter *targets-run*
"
   (run   :doc \"run {{name}}\"
          :load \"{{name}}\" :call (\"{{name}}:main\"))"
  "The `run` target injected for executable non-web templates (cli/agent).")

(defparameter *targets-web*
"
   (serve :doc \"serve {{name}} on :8080 (HOST=0.0.0.0 for LAN)\"
          :load \"{{name}}\" :call (\"{{name}}:serve\" :host host))
   (dev   :doc \"serve + a REPL for interactive development (HOST=0.0.0.0 for LAN)\"
          :interactive t
          :load \"{{name}}\" :call (\"{{name}}:start\" :host host))"
  "The `serve` + `dev` targets injected for the :web template.")

(defparameter *targets-bin*
"
   ;; save-lisp-and-die dumps the image and EXITS, so it cannot run in cons's warm
   ;; image -- a :sh target is always a subprocess sbcl. Loads scripts/build-{{name}}.lisp.
   (bin   :doc \"dump the standalone bin/{{name}} executable\"
          :sh (\"sbcl\" \"--dynamic-space-size\" \"4096\" \"--non-interactive\"
                      \"--load\" \"scripts/build-{{name}}.lisp\"))"
  "The `bin` target injected for executable templates -- dumps a native binary.")

;;; --- the target-kind registry ----------------------------------------------
;;;
;;; Closed and versioned with cons, unlike the templates -- which is why this one stays
;;; here as code while those became directories under cons/templates/.

(setf *target-kinds*
      (list
       (%make-target-kind :name :lib)
       (%make-target-kind
        :name :cli :executable-p t
        :extra-targets (concatenate 'string *targets-run* *targets-bin*)
        :run-line "
    cons run     # run it
    cons bin     # dump a native bin/{{name}}")
       (%make-target-kind
        :name :web :executable-p t
        :spec-params *spec-params-web*
        :extra-targets (concatenate 'string *targets-web* *targets-bin*)
        :run-line "
    cons serve   # run the web app on http://127.0.0.1:8080
    cons bin     # dump a native bin/{{name}}")
       ;; Declared, not yet scaffolded -- the verbs behind them are #37 (service), #78/#72
       ;; (desktop) and design §3a (shared-lib). Named here so a template can already
       ;; declare one and say plainly that its ship path is unbuilt.
       (%make-target-kind :name :desktop :executable-p t :implemented-p nil)
       (%make-target-kind :name :service :executable-p t :implemented-p nil)
       (%make-target-kind :name :shared-lib :implemented-p nil)))

;;; --- the scaffolder -------------------------------------------------------

(defun scaffold (name &key (template :lib) (target (uiop:getcwd))
                           (author *default-author*))
  "Scaffold a new project NAME under TARGET/NAME/ from TEMPLATE. Writes the full
\"just works\" skeleton and returns the project root pathname.

TEMPLATE names what files you start with; the TARGET KIND it declares decides whether the
project has an entry point and what its cons.lisp offers. `cons init --template agent` and
`--template cli` produce the same shape from different dependencies for exactly that
reason."
  (let* ((tmpl (resolve-template template))
         (kind (template-kind tmpl))
         (root (ensure-directories-exist
                (merge-pathnames (format nil "~A/" name) target)))
         ;; What the TEMPLATE supplies: files and dependencies. What the KIND supplies:
         ;; the entry-point-shaped parts of the generated cons.lisp and README. A template
         ;; asks for the latter by marker without knowing what its kind will put there.
         (subs (list (cons "{{spec-params}}"   (target-kind-spec-params kind))
                     (cons "{{targets-extra}}" (target-kind-extra-targets kind))
                     (cons "{{run-line}}"      (target-kind-run-line kind))
                     (cons "{{deps}}" (%render-deps (template-dependencies tmpl)))
                     (cons "{{author}}" author)
                     (cons "{{dev-port}}" (princ-to-string (dev-port name)))
                     (cons "{{name}}" name))))
    (unless (target-kind-implemented-p kind)
      ;; Not an error: files plus an honest warning beat the kind not existing (design §3).
      (format t "~&NOTE: target kind ~(~A~) is declared but its build/ship path is not implemented yet.~%"
              (target-kind-name kind)))
    (format t "Scaffolding ~A (~(~A~)) in ~A~%" name (template-name tmpl) root)
    (let ((files-root (template-files-root tmpl)))
      (dolist (relpath (%tree-files files-root))
        (let ((destination (%substitute-path relpath subs)))
          (%copy-file (merge-pathnames relpath files-root)
                      (merge-pathnames destination root)
                      subs)
          (format t "  create ~A~%" destination))))
    ;; The AI-conformance pack (AGENTS.md + .cursor/rules + .claude/skills) so an IDE
    ;; assistant generates spec-conformant code. CLAUDE.md comes from the template, so
    ;; install without :with-claude (it would be skipped anyway, but be explicit).
    (cons/conform:install-conformance root :name name :with-claude nil)
    ;; Fold every dependency's declared configuration keys into this project's own
    ;; .env.example (pre-publication issue 120). Without this the app author has to find them by reading each
    ;; dependency's source, which drifts the moment a library adds a key -- and the failure
    ;; that follows is a runtime configuration-error deep inside that library, nowhere near
    ;; anything they just changed. Appends, so the template's own file survives; run
    ;; `cons env --write` again after adding a dependency.
    ;;
    ;; Dependencies are passed explicitly because the project is not on the ASDF path yet:
    ;; it was created a moment ago and nothing has registered it. A dependency that is not
    ;; installed here is skipped rather than fatal -- scaffolding must work before the
    ;; dependencies are fetched.
    (handler-case
        (cons/env-scan:sync name
                            :path (merge-pathnames cons/env-scan:*example-name* root)
                            :dependencies (template-dependencies tmpl))
      (error (e)
        (format t "  (skipped .env.example aggregation: ~A)~%" e)))
    (format t "Done. Next: cd ~A && cons ~A~%" name
            (if (eq (target-kind-name kind) :web) "serve" "build"))
    root))
