;;;; setup.lisp --- `cons setup`: put a project on the ASDF path, the monorepo way.
;;;;
;;;; The generalized, cross-OS form of what bootstrap.lisp does for ouranos itself.
;;;; bootstrap.lisp seeds ONE repo (writes 50-ouranos.conf, builds bin/cons); once
;;;; you have bin/cons, `cons setup` does the same drop-in write for ANY project it's
;;;; run in -- a consuming app or a scaffolded app. That is the whole "put me on
;;;; the load path" step in the monorepo era: no local-projects symlink, no clone.
;;;;
;;;; The path MUST be computed in Lisp, not guessed in shell: uiop:xdg-config-home
;;;; resolves to the location ASDF actually reads on every OS (~/.config on Unix,
;;;; %LOCALAPPDATA%\config on Windows, or the XDG override), and ASDF reads the
;;;; drop-in via the same function -- so writer and reader agree by construction.
;;;; Removing stale symlinks is OS-native (symlink vs Windows junction), so that
;;;; stays in the shell setup scripts; here we only DETECT and report them.
;;;; uiop-only (cons stays dependency-light).

(in-package #:cons/setup)

(defun %config-dir ()
  "ASDF's user source-registry.conf.d directory -- per-OS via uiop, matching where
bootstrap.lisp writes and ASDF reads."
  (uiop:xdg-config-home "common-lisp" "source-registry.conf.d/"))

(defun %local-projects ()
  "Quicklisp's local-projects directory (QUICKLISP_HOME or ~/quicklisp), or NIL when
absent -- used only to DETECT a stale pre-drop-in self-symlink."
  (let* ((home (uiop:ensure-directory-pathname
                (or (uiop:getenv "QUICKLISP_HOME")
                    (merge-pathnames "quicklisp/" (user-homedir-pathname)))))
         (lp (merge-pathnames "local-projects/" home)))
    (uiop:directory-exists-p lp)))

(defun %write-drop-in (name root priority dir)
  "Write DIR/<priority>-<NAME>.conf as a `(:tree ROOT)` drop-in; return its path.
Forward slashes so the Lisp reader accepts the path on Windows too."
  (let ((conf (merge-pathnames (format nil "~2,'0D-~A.conf" priority name)
                               (uiop:ensure-directory-pathname dir))))
    (ensure-directories-exist conf)
    (with-open-file (out conf :direction :output
                              :if-exists :supersede :if-does-not-exist :create)
      (format out ";;;; Generated by `cons setup` -- machine-local, do not commit.~%(:tree \"~A\")~%"
              (substitute #\/ #\\ (namestring (uiop:ensure-directory-pathname root)))))
    conf))

(defun %stale-self-link (name root lp)
  "Return LP/<NAME> when it exists as a DIFFERENT path that resolves to ROOT (a stale
pre-drop-in self-symlink now shadowed by the drop-in), else NIL. Never flags a real
directory that simply IS ROOT."
  (when lp
    (let ((entry (merge-pathnames (make-pathname :directory (list :relative name)) lp)))
      (and (uiop:directory-exists-p entry)
           (not (uiop:pathname-equal (uiop:ensure-directory-pathname entry)
                                     (uiop:ensure-directory-pathname root)))
           (ignore-errors
             (uiop:pathname-equal (truename entry) (truename root)))
           entry))))

(defun setup (&key (root (cons/project:project-root)) (priority 60)
                   (config-dir (%config-dir)) (local-projects (%local-projects)))
  "Put the project rooted at ROOT on the ASDF path the monorepo way: write its
source-registry `(:tree)` drop-in as PRIORITY-<name>.conf under CONFIG-DIR (default
the per-OS ASDF config dir), so `(ql:quickload :<name>)` resolves from the current
checkout with no symlink. Notes a stale pre-drop-in self-symlink if it finds one (the
shell setup script removes it). Returns the drop-in path."
  (let* ((root (uiop:ensure-directory-pathname root))
         (name (project:system-name root))
         (conf (%write-drop-in name root priority config-dir)))
    (format t "~&cons setup: wrote ~A~%              (~A now on the ASDF path via (:tree))~%"
            (uiop:native-namestring conf) name)
    (let ((stale (%stale-self-link name root local-projects)))
      (when stale
        (format t "cons setup: note -- ~A is a stale local-projects symlink shadowing~%~14Tthe drop-in; remove it (your setup script does).~%"
                (uiop:native-namestring stale))))
    conf))
